name: VitalSpawn
version: @version@
main: com.tamrielnetwork.vitalspawn.VitalSpawn
api-version: 1.17
authors: [ Tamriel Network ]
website: https://tamriel.site
description: Gives you the ability to set a spawn.
commands:
  vitalspawn:
    description: "Main command"
    usage: "/vitalspawn"
permissions:
  vitalspawn.spawn:
    description: "Permission to teleport to spawn"
    default: op
  vitalspawn.setspawn:
    description: "Permission to set spawn"
    default: op
  vitalspawn.onspawn:
    description: "Permission to teleport to spawn on spawn"
    default: op
  vitalspawn.onrespawn:
    description: "Permission to teleport to spawn on respawn"
    default: op